0: # Стандартное меню геймплея (Говорить/Вещи/ПСИ/т.д.)
  Height: 6 # 8
  Width: 15
  X Offset: 1
  Y Offset: 1
1: # Стандартное диалоговое окно
  Height: 8
  Width: 30 #19
  X Offset: 1 #12
  Y Offset: 1
2: # Окно инвентаря
  Height: 16
  Width: 25 #24
  X Offset: 7
  Y Offset: 1
3: # Окно Исп./Дать/Брос./Помщ.
  Height: 10
  Width: 7
  X Offset: 1
  Y Offset: 1
4: # Описание ПСИ (Затратность ОП и цели)
  Height: 6
  Width: 11
  X Offset: 20
  Y Offset: 1
5: # Меню телефона
  Height: 16
  Width: 12 # 11
  X Offset: 19 # 20
  Y Offset: 1
6: # Меню экипировки (слоты)
  Height: 10
  Width: 23
  X Offset: 8
  Y Offset: 1
7: # Список экипируемых предметов
  Height: 10 # 16
  Width: 15
  X Offset: 16
  Y Offset: 1
8: # Окно Статус
  Height: 18
  Width: 30
  X Offset: 1
  Y Offset: 1
9: # Магазин
  Height: 18
  Width: 19
  X Offset: 12
  Y Offset: 1
10: # Окно с кол-вом налички
  Height: 4
  Width: 8
  X Offset: 1
  Y Offset: 8 # 10
11: # ???
  Height: 4
  Width: 11
  X Offset: 1
  Y Offset: 15
12: # Магазин/Список состояний в ATM Debug Menu
  Height: 16
  Width: 19
  X Offset: 12
  Y Offset: 1
13: # ???
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
14: # Окно сообщений в бою
  Height: 6
  Width: 24
  X Offset: 4
  Y Offset: 1
15: # Среднее окно команд в бою
  Height: 6
  Width: 30 #24
  X Offset: 1
  Y Offset: 1
16: # Окно ПСИ (Атака/Лечение/Вспом.) в бою
  Height: 8
  Width: 8
  X Offset: 1 #4
  Y Offset: 9 #1
17: # Отображаемое название ПСИ при её выборе в бою
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
18: # Малое окно команд в бою (окно Джеффа)
  Height: 6
  Width: 16
  X Offset: 1
  Y Offset: 1
19: # Выбор сохранения (3 файла) после заставки
  Height: 8
  Width: 30
  X Offset: 1
  Y Offset: 2
20: # Окно опций сохранения (Продолжить/Копировать/Настроить/т.д.)
  Height: 4
  Width: 28
  X Offset: 2
  Y Offset: 9
21: # Копирование сохранения (доступны 2 слота)
  Height: 8
  Width: 12
  X Offset: 10
  Y Offset: 16
22: # Копирование сохранения (доступен 1 слот)
  Height: 6
  Width: 12
  X Offset: 10
  Y Offset: 16
23: # Подтверждение удаления/стирания сохранения
  Height: 10
  Width: 21
  X Offset: 6
  Y Offset: 17
24: # Выбор скорости текста
  Height: 10
  Width: 16
  X Offset: 3
  Y Offset: 14
25: # Выбор режима звука (Моно/Стерео)
  Height: 8
  Width: 18
  X Offset: 8
  Y Offset: 15
26: # Ввод имени персонажа (при выдаче имён)
  Height: 4
  Width: 8
  X Offset: 5
  Y Offset: 4
27: # Сообщения "Пожалуйста, назовите его.", "Её тоже." и т.п.
  Height: 4
  Width: 17
  X Offset: 13
  Y Offset: 4
28: # Большое окно с "клавиатурой"
  Height: 16
  Width: 30
  X Offset: 1
  Y Offset: 9
29: # Подтверждение имени Несса
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 3
30: # Подтверждение имени Полы
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 7
31: # Подтверждение имени Джеффа
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 11
32: # Подтверждение имени Пу
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 15
33: # Подтверждение имени питомца
  Height: 4
  Width: 8
  X Offset: 20
  Y Offset: 3
34: # Подтверждение названия любимой еды
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 7
35: # Подтверждение названия любимой вещи
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 13
36: # Подтверждение "Вы уверены?" (после выдачи имён)
  Height: 4
  Width: 24
  X Offset: 4
  Y Offset: 21
37: # Выбор действий Целителя/Выбор размера пиццы у Мач Пицца (достаточно пространства для 3-х пунктов меню)
  Height: 8
  Width: 13
  X Offset: 18
  Y Offset: 6
38: # ???
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
39: # ???
  Height: 6
  Width: 26
  X Offset: 3
  Y Offset: 3
40: # Вспомогательное окошко "Кто?", "Что?", "Кому?", "Где?" и т.п.
  Height: 4
  Width: 7
  X Offset: 1
  Y Offset: 1
41: # Горизонтальное окно с выбором персонажа (2 пункта) из текущей пати
  Height: 4
  Width: 15
  X Offset: 16
  Y Offset: 8
42: # Горизонтальное окно с выбором персонажа (3 пункта) из текущей пати
  Height: 4
  Width: 21
  X Offset: 10
  Y Offset: 8
43: # Горизонтальное окно с выбором персонажа (4 пункта) из текущей пати
  Height: 4
  Width: 27
  X Offset: 4
  Y Offset: 8
44: # Передача предмета другому персонажу
  Height: 16
  Width: 25 # 24
  X Offset: 7 # 8
  Y Offset: 2
45: # Статы в меню экипировки
  Height: 12 #6
  Width: 15
  X Offset: 2 # 3
  Y Offset: 13 # 11
46: # Окно ПСИ (Атака/Лечение/Вспом./Прочее) ВНЕ боя
  Height: 10
  Width: 8
  X Offset: 1 #4
  Y Offset: 9 #1
47: # Окно при повреждённом сохранении, окно с информацией ПСИ
  Height: 11 #10
  Width: 30
  X Offset: 1
  Y Offset: 9
48: # Большое окно команд в бою (окно лидера)
  Height: 6
  Width: 30 #24
  X Offset: 1
  Y Offset: 1
49: # Выбор врага (отображает его имя) в бою
  Height: 4
  Width: 20
  X Offset: 10
  Y Offset: 4
50: # Окно с выбором стиля окон (Обычная начинка, Клубничная и т.д.)
  Height: 16
  Width: 15
  X Offset: 14
  Y Offset: 11
51: # Горизонтальное окно с выбором персонажа (1 пункт) из текущей пати. Обычно не встречается, используется только в Debug Menu
  Height: 4
  Width: 9
  X Offset: 22
  Y Offset: 8
52: # ??? (Используется в качестве окна "Устройчивость")
  Height: 14 # 18
  Width: 13 # 17
  X Offset: 17 # 15
  Y Offset: 13 # 9
