0: #The standard gameplay menu (talk to/goods/PSI/etc.)
  Height: 8
  Width: 15
  X Offset: 1
  Y Offset: 1
1: # Стандартное диалоговое окно
  Height: 8
  Width: 30 #19
  X Offset: 1 #12
  Y Offset: 1
2:
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
3: # Окно Исп./Дать/Брос./Помщ.
  Height: 10
  Width: 7
  X Offset: 1
  Y Offset: 1
4: # Описание ПСИ (Цена и цели)
  Height: 6
  Width: 11
  X Offset: 20
  Y Offset: 1
5:
  Height: 16
  Width: 11
  X Offset: 20
  Y Offset: 1
6:
  Height: 10
  Width: 20
  X Offset: 8
  Y Offset: 1
7: # Список экипируемых предметов
  Height: 12 # 16
  Width: 13
  X Offset: 18
  Y Offset: 1
8:
  Height: 18
  Width: 30
  X Offset: 1
  Y Offset: 1
9:
  Height: 18
  Width: 19
  X Offset: 12
  Y Offset: 1
10:
  Height: 4
  Width: 8
  X Offset: 1
  Y Offset: 10
11:
  Height: 4
  Width: 11
  X Offset: 1
  Y Offset: 15
12:
  Height: 16
  Width: 19
  X Offset: 12
  Y Offset: 1
13:
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
14: # Окно сообщений в бою
  Height: 6
  Width: 24
  X Offset: 4
  Y Offset: 1
15: # Среднее окно команд в бою
  Height: 6
  Width: 30 #24
  X Offset: 1
  Y Offset: 1
16: # Окно ПСИ (Атака/Лечение/Вспом.) В бою
  Height: 8
  Width: 8
  X Offset: 1 #4
  Y Offset: 9 #1
17:
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
18: # Малое окно команд в бою (окно Джеффа)
  Height: 6
  Width: 16
  X Offset: 1
  Y Offset: 1
19:
  Height: 8
  Width: 30
  X Offset: 1
  Y Offset: 2
20: #Continue/Copy/SetUp/etc. window
  Height: 4
  Width: 27
  X Offset: 2
  Y Offset: 9
21:
  Height: 8
  Width: 12
  X Offset: 10
  Y Offset: 16
22:
  Height: 6
  Width: 12
  X Offset: 10
  Y Offset: 16
23:
  Height: 10
  Width: 21
  X Offset: 6
  Y Offset: 17
24:
  Height: 10
  Width: 16
  X Offset: 3
  Y Offset: 14
25:
  Height: 8
  Width: 18
  X Offset: 8
  Y Offset: 15
26:
  Height: 4
  Width: 8
  X Offset: 5
  Y Offset: 4
27:
  Height: 4
  Width: 17
  X Offset: 13
  Y Offset: 4
28:
  Height: 16
  Width: 30
  X Offset: 1
  Y Offset: 9
29:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 3
30:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 7
31:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 11
32:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 15
33:
  Height: 4
  Width: 8
  X Offset: 20
  Y Offset: 3
34:
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 7
35:
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 13
36:
  Height: 4
  Width: 24
  X Offset: 4
  Y Offset: 21
37:
  Height: 8
  Width: 13
  X Offset: 18
  Y Offset: 6
38:
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
39:
  Height: 6
  Width: 26
  X Offset: 3
  Y Offset: 3
40:
  Height: 4
  Width: 7
  X Offset: 1
  Y Offset: 1
41:
  Height: 4
  Width: 15
  X Offset: 16
  Y Offset: 8
42:
  Height: 4
  Width: 21
  X Offset: 10
  Y Offset: 8
43:
  Height: 4
  Width: 27
  X Offset: 4
  Y Offset: 8
44:
  Height: 16
  Width: 24
  X Offset: 8
  Y Offset: 2
45: # Статы в меню экипировки
  Height: 12 #6
  Width: 15
  X Offset: 0 # 3
  Y Offset: 13 # 11
46: # Окно ПСИ (Атака/Лечение/Вспом./Прочее) ВНЕ боя
  Height: 10
  Width: 8
  X Offset: 1 #4
  Y Offset: 9 #1
47: #Повреждённое окно при сохранении игры, окно с информацией ПСИ
  Height: 11 #10
  Width: 30
  X Offset: 1
  Y Offset: 9
48: # Большое окно команд в бою (окно лидера)
  Height: 6
  Width: 30 #24
  X Offset: 1
  Y Offset: 1
49:
  Height: 4
  Width: 20
  X Offset: 10
  Y Offset: 4
50: # Окно с выбором стиля (Обычная начинка, Клубничная и т.д.)
  Height: 16
  Width: 15
  X Offset: 14
  Y Offset: 11
51:
  Height: 4
  Width: 9
  X Offset: 22
  Y Offset: 8
52: # ???
  Height: 14 # 18
  Width: 17 # 18
  X Offset: 15 # 7
  Y Offset: 13 # 9
